# Star Wars 1977 70mm Broad Net Tracker

[target]
theater = "tx-dallas/cinemark-dallas-xd-and-imax"
theatre_url = "https://www.imax.com/movie/star-wars-50th-anniversary"

[filters]
excluded_rows = [] 
date = "2027-02-19"
earliest_showtime = "09:00"
latest_showtime = "23:59"
party_size = 1
